### ISSUE TITLE
error on running the tool

### ISSUE THREAD

**Issue by nkada** [manekinekko/angular2-dependencies-graph#11]
I just installed the tool and try to generate the dependency graph. 

I get the following error:

Cannot read property 'indexOf' of undefined.
![image](https://cloud.githubusercontent.com/assets/1577989/14751835/e220c4f2-08c3-11e6-806a-492d5dee4510.png)

**Comment by nkada** [comment]
If the tool is run without options, it assumes that you have exclude section in tsconfig.json
![image](https://cloud.githubusercontent.com/assets/1577989/14752115/49147392-08c5-11e6-9ce6-0a0d09b96636.png)

**Comment by manekinekko** [comment]
fixed in https://github.com/manekinekko/angular2-dependencies-graph/releases/tag/v0.2.6
