### ISSUE TITLE
Missing gulp-util

### ISSUE THREAD

**Issue by ldex** [manekinekko/angular2-dependencies-graph#14]
Works great!
The only thing is I had to install gulp-util before.

**Comment by manekinekko** [comment]
what's your NPM version ?

**Comment by ldex** [comment]
2.14.20

**Comment by manekinekko** [comment]
Could you try with NPM 3 and let me know?

On Tue, May 17, 2016, 04:57 ldex <notifications@github.com> wrote:

> 2.14.20
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/manekinekko/angular2-dependencies-graph/issues/14#issuecomment-219607221>
>
-- 

Wassim Chegham
Developer Advocate at SFEIR
Google Developer Expert in Web Technologies
<http://fr.linkedin.com/in/wassimchegham>  <http://twitter.com/manekinekko>
<http://plus.google.com/+WassimCheghamJavaScript/posts>
<http://flickr.com/photos/manekinekko/albums/>
<http://github.com/manekinekko>  <http://wassimchegham.com/feed>
<http://wassimchegham.com/>  <http://www.meetup.com/members/135357292/>
<http://slides.com/wassimchegham/>

**Comment by manekinekko** [comment]
fixed in https://github.com/manekinekko/angular2-dependencies-graph/releases/tag/v0.2.9
