### ISSUE TITLE
Support ability to specify version of TypeScript

### ISSUE THREAD

**Issue by mko** [manekinekko/angular2-dependencies-graph#15]
Once I got the app running, it did a fantastic job on the simpler test cases I threw at it. Unfortunately, it fails when running on our larger, more complex application due to the fact that our module resolution method utilizes a feature only available in newer versions of TypeScript (1.9.x nightlies) called [Path Mapping](https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md#path-mapping). It greatly simplifies the module declarations throughout the system (important in larger applications), but with TypeScript 1.7.3, the app fails to recognize pretty much the entirety of our component tree after the parent app component.

**Comment by mko** [comment]
Note: I'm not sure just specifying TypeScript version will fix the issue, as I don't know what's under the hood doing the module resolution in your app, so this might be a bigger fix than I think it is. If it is, I'll just give up on good tooling until TypeScript 2.0RC is in the wild.

**Comment by manekinekko** [comment]
thanks @mko 
I need to find some time to look at TS 2.0

**Comment by manekinekko** [comment]
@mko could you provide a simple test case where this tool fails to crawl your app?

**Comment by manekinekko** [comment]
the tool now supports typescript 2.
