### ISSUE TITLE
Add a VSCode extension 

### ISSUE THREAD

**Issue by manekinekko** [manekinekko/angular2-dependencies-graph#17]
We could have a Visual Studio Code extension version of this tool.
Some examples : https://code.visualstudio.com/Docs/extensions/example-hello-world

**Comment by web-dave** [comment]
finished with --tsconfig (Project based)
btw. could you although generate md file. or let me contribute you to add these 5 lines.
now i stuck while Publishing the Extension. ;(

**Comment by manekinekko** [comment]
@web-dave can you clarify your thoughts please ?

**Comment by web-dave** [comment]
This were two topics in one sentence. Sorry.

1. Generate although md files. (*.md). I'll make a pullrequest.
2. I get an error while publishing to vscode ext store. So this is no topic for you, just info.

**Comment by web-dave** [comment]
Got a answer from vscode team. The package is to big. Max size is 20mb. Shop I have to refactor the plugin.

**Comment by manekinekko** [comment]
may be we could move some deps to `devDependencies` in package.json. For instance: `conventional-changelog-cli` and `typings` don't have to be installed in prod mode.

**Comment by web-dave** [comment]
Another idea is to hold ago the code in the plugin. 
Now I set this module as adepedency. 
Some dependencies are now duplicated.
I try this weekend.

**Comment by web-dave** [comment]
published right now

https://marketplace.visualstudio.com/items?itemName=web-dave.ng2-dg

**Comment by strpipe** [comment]
Many thanks for this. Is there a way to change the settings somehow? All my components are beneath each other. The only dependencies shown in the svg are from a component to its .html file.
