### ISSUE TITLE
is there an option to exclude all css, html files from output

### ISSUE THREAD

**Issue by tbuffryslb** [manekinekko/angular2-dependencies-graph#24]

**Comment by vogloblinsky** [comment]
[-> Pull requested](https://github.com/manekinekko/angular2-dependencies-graph/pull/25)

**Comment by manekinekko** [comment]
fixed in https://github.com/manekinekko/angular2-dependencies-graph/commit/23fee0c662646724bc545e7b604d3d84bb82a816 thanks to @vogloblinsky 
See readme for more details
