### ISSUE TITLE
Add a legend with graph

### ISSUE THREAD

**Issue by vogloblinsky** [manekinekko/angular2-dependencies-graph#27]
- by default ?
- option ?
- just colors : type of element ?

An example : 

![](https://pbs.twimg.com/media/CvGgsTAWAAIfvNA.jpg)

**Comment by manekinekko** [comment]
fixed in https://github.com/manekinekko/angular2-dependencies-graph/commit/b6ecf4489cc604ad2edac55b8970b985fc9498b2 thanks to @vogloblinsky
