### ISSUE TITLE
Not retrieving all modules

### ISSUE THREAD

**Issue by vogloblinsky** [manekinekko/angular2-dependencies-graph#35]
Using this open-source Angular 2 application : https://github.com/r-park/soundcloud-ngrx

I didn't get in the outputed json modules like : HomeModule, BrowserModule, CoreModule for examples.

The graph is below.

![dependencies](https://cloud.githubusercontent.com/assets/2841805/19875715/5269eec6-9fcf-11e6-8b08-f25cdabb531f.jpg)

Is it because they don't have "imports" ?

**Comment by manekinekko** [comment]
that's because this tool doesn't understand providers configurations yet: `{provide: APP_BASE_HREF, useValue: '/'}`.

I'm working on it.

**Comment by manekinekko** [comment]
It's working now. Pushed to [v1.0.0-alpha.7](https://www.npmjs.com/package/angular2-dependencies-graph)

![dependencies-1](https://cloud.githubusercontent.com/assets/1699357/19880628/3ca1a3ba-9fff-11e6-9097-9ad8c7d2c4b3.png)

**Comment by vogloblinsky** [comment]
Thanks, i commented the line for getting the main graph.
But with v1.0.0-alpha.7 i always missing HomeModule for example in the array of modules in dependencies.json, is there any reason ?

**Comment by manekinekko** [comment]
are you talking about the `imports` entry in `dependencies.json`?

![image](https://cloud.githubusercontent.com/assets/1699357/19889063/1cf05b72-a033-11e6-9b61-d3717f8c75e1.png)

**Comment by manekinekko** [comment]
Alrigh. I figure out what you mean. Let me check...

**Comment by vogloblinsky** [comment]
No, the global list of modules in the main array of the json.
With some research, it seems that tsc.getSourcesFiles() didn't find HomeModule index.ts file if it not included in src/main.ts

Vincent

**Comment by manekinekko** [comment]
yep. That's what I found out also. I'll dig more to find out why.

**Comment by manekinekko** [comment]
Problem solved. I basically had to override the `ts.CompilerHost` interface.

Is the following graph OK?

![dependencies-2](https://cloud.githubusercontent.com/assets/1699357/19892820/17dac1a4-a047-11e6-93ae-25fa730f4b1b.png)

**Comment by manekinekko** [comment]
Pushed to [v1.0.0-alpha.8](https://www.npmjs.com/package/angular2-dependencies-graph)
