### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by pantonis** [manekinekko/angular2-dependencies-graph#4]
Hi,

this package cannot be installed. I have attached the log file from npm
[npm-debug.txt](https://github.com/manekinekko/angular2-dependencies-graph/files/162601/npm-debug.txt)

**Comment by manekinekko** [comment]
@pantonis do you have `typescript` and `typings` installed globally ?

**Comment by pantonis** [comment]
Yes that was the problem. Very useful tool!!! Thanks.
