### ISSUE TITLE
bug: node 7?

### ISSUE THREAD

**Issue by vogloblinsky** [manekinekko/angular2-dependencies-graph#40]
Why node versions > 7.0.0 not compatible ?

**Comment by cojack** [comment]
@manekinekko could you guide us?

**Comment by manekinekko** [comment]
The package needs to be tested with Node7. If everything is OK, I'll update this: https://github.com/manekinekko/angular2-dependencies-graph/blob/master/package.json#L21

**Comment by manekinekko** [comment]
@cojack wanna take this? I don't have access to Node7 right now...

**Comment by vogloblinsky** [comment]
@manekinekko done 😉 
PR : https://github.com/manekinekko/angular2-dependencies-graph/pull/41

**Comment by manekinekko** [comment]
merged.
