### ISSUE TITLE
Support apps without "files" attribute / with "exclude" attribute

### ISSUE THREAD

**Issue by bitsmag** [manekinekko/angular2-dependencies-graph#6]
If there is no "files" Attribute, the typescript Compiler simply includes all typescript files. If there is a "exclude" attribute the typescript compiler includes all typescript files except the ones which are specified in the exclude array [http://www.typescriptlang.org/docs/handbook/tsconfig.json.htm](http://www.typescriptlang.org/docs/handbook/tsconfig.json.html). I think it would make sense if this tool would do the same.

I quickly put some code together to make it possible for my application to use the tool. Not sure if it is super clean, but it works for me.

In `application.ts`, instead of:

    if(!files) {
      logger.fatal('"tsconfig.json" file does not export a "files" attriute');
      process.exit(1);
    }

I do:

    if(!files) {

      let exclude = [];
      exclude = require(program.tsconfig).exclude;

      var walk = function(dir) {
        var results = [];
        var list = fs.readdirSync(dir);
        list.forEach(function(file) {
          if (exclude.indexOf(file) < 0) {
            file = dir + '/' + file;
            var stat = fs.statSync(file);
            if (stat && stat.isDirectory()) results = results.concat(walk(file));
            else if (path.extname(file) === '.ts') results.push(file)
          }
        });
        return results
      };

      files = walk('.');

    }

**Comment by manekinekko** [comment]
@pitsmag thanks for this. Do you think you can send a PR?

**Comment by bitsmag** [comment]
Sure :)

**Comment by manekinekko** [comment]
Featured landed in 0.2.2 (see commit https://github.com/manekinekko/angular2-dependencies-graph/commit/e68e31e404e8cad3104fd85d8f6056db3cb120e1). Thanks man.
